version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    user: root
    privileged: true
    ports:
    - 30001:30001
    - 50000:50000
    environment:
    - TZ=Asia/Seoul
    - JENKINS_OPTS=--httpPort=30001
    - JAVA_ARGS=-Xmx4096m
    volumes:
    - ../jenkins/workspace:/var/jenkins_home/workspace
    - /var/run/docker.sock:/var/run/docker.sock